WELCOME_HEADER = "Welcome to Isolation!"
CHOOSE_DIFFICULTY_HEADER = "Choose difficulty"
CHOOSE_PVP_TYPE_HEADER = "Choose PvP type"
CHOOSE_ROLE_HEADER = "Choose role"
CREATE_GAME_HEADER = "Create a game"
JOIN_GAME_HEADER = "Join a game"

PVE_BUTTON = "Play with computer"
PVP_BUTTON = "Play with a friend"
QUIT_BUTTON = "Quit"
EASY_BUTTON = "Easy"
NORMAL_BUTTON = "Normal"
HARD_BUTTON = "Hard"
BACK_BUTTON = "< Back"
THIS_COMPUTER_BUTTON = "This computer"
TWO_COMPUTERS_BUTTON = "Two computers"
CONNECT_BUTTON = "Connect"
CREATE_AND_WAIT = "Create and wait"
JOIN_BUTTON = "Join"
HOST_BUTTON = "Host"

PORT_INPUT = "Port:  "
HOST_INPUT = "Host:  "
